import Head from 'next/head'
import Image from 'next/image'
import Layout from '../../components/Layout/Layout'
import styles from '../../styles/ContactUs.module.css'
import contactUsImg from '../../public/images/contact-us.jpeg'

const ContactUs = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="NextJS Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className={styles.contactUs}>
          <div className={styles.bannerContainer}>
            <Image src={contactUsImg} alt='Contact us Banner' />
          </div>
          <div className={styles.form}>
            <h1>Contact Us</h1>
          </div>
        </div>
      </Layout>
    </div>
  )
}

export default ContactUs