import Head from 'next/head'
import Layout from '../../components/Layout/Layout'
import styles from '../../styles/Users.module.css'

// Server side doesn't rquire staticPaths because is not pre-generated
// Note: This code is not included in JS bundles
export const getServerSideProps = async (context) => {
  try {
    // Difference from getStaticProps
    const { params, req, res} = context
    const response = await fetch('https://movies-71584-default-rtdb.firebaseio.com/users.json')
    const data = await response.json()

    return {
      props: {
        users: { ...data }
      }
    }
  } catch (error) {

    return {
      props: {
        users: { error: 'Error: Could not get data' }
      }
    }
  }
}

const users = ({ users }) => {
  if (users?.error) {
    return <p>An error occured: {movies?.error}</p>
  }

  return (
    <div>
      <Head>
        <title>NextJS Workshop</title>
        <meta name="description" content="NextJS Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className={styles.usersList}>
          <h1>Users</h1>
          <div>{Object.keys(users).map((key) => (
            <div className={styles.userInfo} key={key}>
              <div className={styles.user}><h2>{users[key]?.name}</h2></div>
              <div className={styles.info}>
                <p><b>Username:</b> {users[key]?.username}</p>
                <p><b>Address:</b> {users[key]?.address}</p>
              </div>
            </div>
          ))}</div>
        </div>
      </Layout>
    </div>
  )
}

export default users