import Head from 'next/head'
import Image from 'next/image'
import Layout from '../../components/Layout/Layout'
import styles from '../../styles/AboutUs.module.css'
import aboutUsImg from '../../public/images/about-us.jpeg'

const AboutUs = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>About Us</title>
        <meta name="description" content="NextJS Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className={styles.aboutUs}>
          <div className={styles.bannerContainer}>
            <Image src={aboutUsImg} alt='About us Banner' />
          </div>
          <div className={styles.boxes}>
            <div>
              <h2>Mission</h2>
              <hr />
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            </div>
            <div>
              <h2>Objectives</h2>
              <hr />
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            </div>
          </div>

        </div>
      </Layout>
    </div>
  )
}

export default AboutUs