import Head from 'next/head'
import { useState, useEffect } from 'react'
import Layout from '../components/Layout/Layout'
import MoviesList from '../components/Movies/MoviesList'
import styles from '../styles/Home.module.css'

// Note: This code is not included in JS bundles
export const getStaticProps = async (context) => {
  try {
    const response = await fetch('https://movies-71584-default-rtdb.firebaseio.com/movies.json')
    const data = await response.json()

    return {
      props: {
        movies: { ...data }
      }
    }
  } catch (error) {

    return {
      props: {
        movies: { error: 'Error: Could not get data' }
      },
      revalidate: 60
    }
  }
}

const Home = ({ movies }) => {
  /* const [movies, setMovies] = useState({})

  const _getMovies = async () => {
    try {
      const response = await fetch('https://movies-71584-default-rtdb.firebaseio.com/movies.json')
      const data = await response.json()

      setMovies(data)
    } catch (error) {
      throw new Error(error)
    }
  }

  useEffect(() => {
    _getMovies()
  }, []) */

  if(movies?.error) {
    return <p>An error occured: {movies?.error}</p>
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Workshop</title>
        <meta name="description" content="NextJS Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <MoviesList movies={movies} />
      </Layout>
    </div>
  )
}

export default Home